# -*- coding: utf-8 -*-

rgou = {"en": "Royal Game of Ur", "de": "Königliches Spiel von Ur", "ru": "Королевская Игра Ура"}
whitebegins = {"en": "White begins", "de": "Weiß beginnt", "ru": "Белые начинают"}
gamestr = {"en": "Game", "de": "Spiel", "ru": "Игра"}
newgame = {"en": "New Game", "de": "Neues Spiel", "ru": "Нлвая Игра"}
exit = {"en": "Exit", "de": "Schließen", "ru": "Закрыть"}
preferences = {"en": "Preferences", "de": "Einstellungen", "ru": "Настройки"}
changelanguage = {"en": "Change language", "de": "Sprache ändern", "ru": "Изменить язык"}
changedifficulty = {"en": "Change difficulty", "de": "Schwierigkeitsgrad", "ru": "Изменить сложность"}
changeruleset = {"en": "Change rule set", "de": "Regeln ändern", "ru": "Изменить правила"}
startasblack = {"en": "Start as black", "de": "Als schwarz anfangen", "ru": "Начать чёрными"}
about = {"en": "About", "de": "Über", "ru": "О игре"}
rules = {"en": "Rules", "de": "Spielregeln", "ru": "Правила"}
aboutgame = {"en": "About the game", "de": "Über das Spiel", "ru": "О игре"}
roll = {"en": "Roll!", "de": "Würfeln!", "ru": "Бросай!"}
outofbounds = {"en": "Out of bounds", "de": "Zu viel", "ru": "Слишком много"}
notclickable = {"en": "Not clickable", "de": "Hier kann man nicht klicken", "ru": "Сюда нельзя"}
notallowed = {"en": "Not allowed", "de": "Nicht erlaubt", "ru": "Невозможно"}
youcant = {"en": "You can't move there", "de": "Du kannst da nicht hin", "ru": "Сюда передвинуть нельзя"}
blacksturn = {"en": "Black's turn", "de": "Schwarz ist am Zug", "ru": "Ход чёрных"}
whitesturn = {"en": "White's turn", "de": "Weiß ist am Zug", "ru": "Ход белых"}
wehaveawinner = {"en": "We have a winner!", "de": "Wir haben einen Gewinner!", "ru": "У нас чемпион!"}
whitewins = {"en": "White wins!", "de": "Weiß gewinnt!", "ru": "Белые выигрывают!"}
blackwins = {"en": "Black wins!", "de": "Schwarz gewinnt!", "ru": "Чёрные выигрывают!"}
skipmove = {"en": "Skip move", "de": "Überspringen", "ru": "Пропустить ход"}
skip = {"en": "Skip move", "de": "Überspringen", "ru": "Пропустить ход"}
info = {"en": "Developed by Andreas Hemmetter \ngithub.com/Ahemmetter/royal-game-of-ur \nahemmetter@gmail.com", "de": "Entwickelt von Andreas Hemmetter \ngithub.com/Ahemmetter/royal-game-of-ur \nahemmetter@gmail.com", "ru": "Сделано от Андреаса Хемметтера \ngithub.com/Ahemmetter/royal-game-of-ur \nahemmetter@gmail.com"}
ruletext = {"en": "The rules for the Royal Game of Ur are fairly straight-forward. Variations exist, but in this program only one ruleset so far is implemented: the British Museum ruleset.\n \n The game board consists of 20 colored squares, arranged three horizontal rows. Each player initially has 7 stones in his color (black or white).\n  \n Players take turns throwing marked tetrahedrons (equivalent to throwing dice with changed probability distribution). The possible outcomes are 0, 1, 2, 3 or 4, where 2 is the most probable. Each player moves any stone the designated number of fields along a certain path with the goal of reaching the end and freeing the stone. The game ends when one player has managed to get all his 7 stones out of the game before the other player.\n  \n A complication is added by two additional rules:\n  \n 1. The players can kick each other back to the start. For this a stone must hop to a field where a stone of another player is already sitting. \n  \n 2. The players can throw the dice again, if they land on a red square (rosette) with their previous move. \n  \n The red squares are spaced 4 fields apart. This means that the game can be efficiently traversed, if the players only throw 4s.", "de": "Die Spielregeln für das Königliche Spiel von Ur sind relativ einfach. Es gibt einige Variationen, aber in diesem Programm wurde nur ein Regelsatz eingebaut: das vom Britischen Museum. \n \n Das Spielfeld besteht aus 20 farbigen Quadraten in drei Reihen. Jeder Spieler hat anfangs 7 Figuren in seiner Farbe (schwarz oder weiß). \n \n Die Spieler wechseln sich ab und werfen angemalte Tetraeder (das ist äquivalent zu einem Würfelwurf mit veränderter Wahrscheinlichkeitsverteilung). Die möglichen Ergebnisse eines Wurfes sind 0, 1, 2, 3 oder 4, wobei 2 die häufigst gewürfelte Zahl ist. Jeder Spieler bewegt eine seiner Figuren die angezeigte Anzahl an Feldern auf seinem Pfad, mit dem Ziel, das andere Ende zu erreichen und seine Figuren freizuspielen. \n \n Es gibt zwei extra Regeln: \n \n 1. Die Spieler können sich gegenseitig aus dem Spiel werfen, falls eine Figur auf ein schon vom Gegner besetztes Feld hüpft. \n \n 2. Die Spieler können noch einmal würfeln, wenn sie mit dem letzten Zug auf einem roten Feld (Rosette) gelandet sind. \n \n Die roten Felder sind je vier Felder auseinander. Das bedeutet, dass man seine Figuren effektiv zum Ziel bringen kann, indem man nur 4 würfelt.", "ru": "Ещё не доступен"}
